name: scube_technologies_task
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  # State Management and Service Locator
  http: ^1.3.0
  get: ^4.7.2 # State Management!
  get_it: ^8.0.3 # locator
  dio: ^5.8.0+1 # Network handling

  # Local Storage
  shared_preferences: ^2.5.3 # Local Storage!
  sqflite: ^2.4.2

  # Localization and Utilities
  intl: ^0.20.2 # Localization and Date Formatting
  pdf: ^3.11.3 # PDF Generation
  path: ^1.9.1
  path_provider: ^2.1.5 # File System Paths
  printing: ^5.14.2
  share_plus: ^11.1.0

  #  share: ^2.0.4 # Sharing Content
  in_app_update: ^4.2.3 # App Update Notifications

  # UI Enhancements
  shimmer: ^3.0.0 # Loading Placeholders
  image_picker: ^1.1.2
  file_picker: ^10.2.1
  #  circular_badge_avatar: ^0.1.5 # Circular Avatars with Badges
  cupertino_icons: ^1.0.8 # iOS-styled Icons
  gif_view: ^1.0.0
  pie_chart: ^5.4.0
  fl_chart: ^0.70.2
  flutter_inappwebview: ^6.1.5

  # Font Style!
  google_fonts: ^6.2.1
  html: ^0.15.4

  # Location!
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  google_maps_flutter: ^2.12.3

  # Utilities!
  marquee: ^2.2.3
  url_launcher: ^6.3.2 # Launch URLs
  device_info_plus: ^11.3.3
  connectivity_plus: ^6.1.3
  permission_handler: ^11.4.0
  flutter_image_compress: ^2.4.0 # Image Compression
  package_info_plus: ^8.3.0
  youtube_player_flutter: ^9.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/app_icons/
    - assets/app_images/
    - assets/app_src/
    - assets/required_image/

